### ISSUE TITLE
citation request

### ISSUE THREAD

**Issue by DatTrongNg** [EBazarov/nsfw_data_source_urls#17]
Hi, 
I want to include your work in on of my project.
How should I cite the dataset?

Thank you for your work!

**Comment by EBazarov** [comment]
Hey @DatTrongNg, be free to do it in the way you prefer. 
No need to cite if you don't want, but be free to do so if you want, up to you ;)

**Comment by DatTrongNg** [comment]
Got it! Thanks for the prompt reply.
