### ISSUE TITLE
Which categories are nsfw and which categories are sfw?

### ISSUE THREAD

**Issue by Ensteinjun** [EBazarov/nsfw_data_source_urls#2]
or all categories are nsfw ?

**Comment by EBazarov** [comment]
Good question thanks.
I think I was not clear in my notes, when I wrote:
> This repository helps in retrieving NSFW images and there's no special URLs for neutral content
I mean that all categories should be taken as NSFW and there's no special SFW categories, but what you should also take in case that data you will retrieve is not pure NSFW and may contain some amount of SFW/sexy images and maybe you will find useful to preprocess it before training model on it.

**Comment by Ensteinjun** [comment]
> Good question thanks.
> I think I was not clear in my notes, when I wrote:
> 
> > This repository helps in retrieving NSFW images and there's no special URLs for neutral content
> 
> I mean that all categories should be taken as NSFW and there's no special SFW categories, but what you should also take in case that data you will retrieve is not pure NSFW and may contain some amount of SFW/sexy images and maybe you will find useful to preprocess it before training model on it.

thank you

**Comment by EBazarov** [comment]
you are welcome
