### ISSUE TITLE
Hexstream's Classy Clop Collection

### ISSUE THREAD

**Issue by Hexstream** [EBazarov/nsfw_data_source_urls#3]
Hello. I have a bunch of fun NSFW stuff here: https://clop.ponies.hexstream.net/

A full list of the ~600 images is here: https://clop.ponies.hexstream.net/meta/all/

Almost all of these images are NSFW.

Please let me know if this dataset might be useful to you.

**Comment by EBazarov** [comment]
Hi, 

Thank you for your proposition, I think community will be happy to use those images, if you will make PR request with list of images URLs I will merge it to master.

Cheers

**Comment by Hexstream** [comment]
Great! I'll do it.

**Comment by Hexstream** [comment]
Category-wise, should this all go into a new "my_little_pony" category or something?
I don't want to find myself sifting through hundreds of categories...

If I just produce a flat list of NSFW URL's, would most of the work be already done before it can be merged?

**Comment by EBazarov** [comment]
you can put it as category `urls_artificial-images_my_little_pony`.
You will need to make folder `artificial-images_my_little_pony` inside `raw_data`. And after put there file `urls_artificial-images_my_little_pony.txt` that will contains list of images URLs (one url per line). That's all, thank you

**Comment by Hexstream** [comment]
Awesome, thanks for the detailed instructions. :)

**Comment by EBazarov** [comment]
You are welcome
