### ISSUE TITLE
image label

### ISSUE THREAD

**Issue by MaybeShewill-CV** [EBazarov/nsfw_data_source_urls#6]
May I ask what's the label of each image? Thanks a lot:)

**Comment by EBazarov** [comment]
Hi, it's up to you to label images, by default you can assume, that most of them is NSFW, after you can split images in `sexy`, `porn` and other categories, but you should do it on your side, this repository doesn't provide such labels. Thanks for your question

**Comment by MaybeShewill-CV** [comment]
@EBazarov Thanka a lot:)
